### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pnzxr** [goodbyepavlyi/DiscordFS#4]
discordfs  |   stack: 'TypeError: crypto.randomBytes is not a function\n' +
discordfs  |     '    at DiscordFileProvider.getAttachmentBuilderFromBuffer (/app/lib/storage/DiscordFileProvider.js:32:30)\n' +
discordfs  |     '    at DiscordFileProvider.uploadChunkToDiscord (/app/lib/storage/DiscordFileProvider.js:52:27)\n' +
discordfs  |     '    at Writable.final [as _final] (/app/lib/storage/DiscordFileProvider.js:112:32)\n' +
discordfs  |     '    at callFinal (node:internal/streams/writable:757:12)\n' +
discordfs  |     '    at prefinish (node:internal/streams/writable:769:7)\n' +
discordfs  |     '    at finishMaybe (node:internal/streams/writable:779:5)\n' +
discordfs  |     '    at Writable.end (node:internal/streams/writable:687:5)\n' +
discordfs  |     '    at Cipher.onend (node:internal/streams/readable:756:10)\n' +
discordfs  |     '    at Object.onceWrapper (node:events:628:28)\n' +
discordfs  |     '    at Cipher.emit (node:events:514:28)'

**Comment by goodbyepavlyi** [comment]
Fixed in the version 1.0.1 (6ae05b4798b2c81a6b41ec8a0bc4f09c4039a484)
