### ISSUE TITLE
MIgration files from other project

### ISSUE THREAD

**Issue by martysl** [goodbyepavlyi/DiscordFS#5]
hello,
i would like to ask if would be possible to make script to migrate from ddrv because it got discontinued
here is a repo backup https://github.com/ImPeekaboo/ddrv and https://hub.docker.com/r/forscht/ddrv original got closed

it use go and postgresql backend. webhook and bots too, cant hide it would be great if possible cause we have a lot of files there and it geting super slow.

**Comment by goodbyepavlyi** [comment]
Hi, you’ll need to reupload files to the WebDAV server to migrate.
